<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KJACJ2C" failures="1" tests="2" name="Add Employee Test" time="123.168" errors="0" timestamp="2024-09-05T13:45:21 IST">
  <testcase classname="Framework.Tests.AddEmployeeTest" name="addAndVerifyEmployee" time="48.013">
    <skipped/>
  </testcase> <!-- addAndVerifyEmployee -->
  <testcase classname="Framework.Tests.AddEmployeeTest" name="addAndVerifyEmployee" time="47.302">
    <failure type="java.lang.AssertionError" message="expected [Successfuly Saved] but found [Successfully Saved]">
      <![CDATA[java.lang.AssertionError: expected [Successfuly Saved] but found [Successfully Saved]
at Framework.Tests.AddEmployeeTest.addAndVerifyEmployee(AddEmployeeTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- addAndVerifyEmployee -->
</testsuite> <!-- Add Employee Test -->
